### PR TITLE
Adding infinite list behavior

### PR DESCRIPTION
**Pull request by joshbedo**
### Overview
- Adding infinite scroll list behavior that @meomix created

### CODE REVIEW

**Comment by MeoMix** [comment]
Oh jeeze. No pressure or anything :p I think there might be a slight optimization I can make to this after I refactor to use onAttach, but cool! Exciting!! :D :+1:

**Comment by joshbedo** [comment]
I figured it's better to have it then not have it at all :) We can make optimizations over-time. Make it work then make it better. Which area are you talking about for using `onAttach`?

**Comment by MeoMix** [comment]
IIRC children get added to a CollectionView before the CollectionView is shown which was making the initial bout of _addChild all result in no-ops because minRenderIndex and maxRenderIndex had yet to be calculated. Then, onShow triggers, and runs through the collection again and figures it all out.

I remember talking to jmeas about this and him saying this would change at some point. That might be a v3 thing, but it might be with onAttach, too. So, gotta take a look.

**Comment by jasonLaster** [comment]
So good. Merging so we can all play!

**Comment by MeoMix** [comment]
:+1: 

My largest complaints with it right now are:

- You need to explicitly tell it what the size is of your ItemView being rendered and they all need to be the same size.
- I defer running some of the logic in OnCollectionRemove to prevent an off-by-one which sucks.
- There's a bug regarding adding a model to a collection at a specific index which can be fixed by calling sort on the collection afterward (because that causes the implementing view to re-draw itself). The issue is that the index the model is being added at in the collection is not the same as the index that the ItemView is being added at in the CollectionView if minRenderIndex is > 0. You can see a comment I made regarding that here: https://github.com/MeoMix/StreamusChromeExtension/blob/master/src/js/foreground/view/behavior/sortable.js#L150

I have to wonder if it would be better to just aggressively re-render the view instead of trying to do a bunch of math to try and touch a smaller amount of elements during specific events.

Anyway, just some things to think about. Would love to have more eyes on this code and happy to answer questions, but I've put more than enough hours into this by myself at the moment. :)

**Pull request merged**
